kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: pod-reader
rules:
  - apiGroups: [""] # The API group "" indicates the core API Group.
    resources: ["pods", "services"]
    verbs: ["delete", "get", "watch", "list"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount # May be "User", "Group" or "ServiceAccount"
    name: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jacky-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jacky-tools
  template:
    metadata:
      labels:
        app: jacky-tools
    spec:
      containers:
      - name: jacky-tools
        image: jacky06/jacky-tools:v2
        command: [ "/bin/sh", "-c", "sleep infinity" ]
        env:
          - name: SPECIAL_METADATA_NAME
            valueFrom:
              fieldRef:
               fieldPath: metadata.name
          - name: SPECIAL_HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
